export const FETCH_TEAMS_REQUEST = 'FETCH_TEAMS_REQUEST'
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS'
export const FETCH_TEAMS_FAILURE = 'FETCH_TEAMS_FAILURE'

export const FETCH_PREVIOUS_TEAMS_REQUEST = 'FETCH_PREVIOUS_TEAMS_REQUEST'
export const FETCH_PREVIOUS_TEAMS_SUCCESS = 'FETCH_PREVIOUS_TEAMS_SUCCESS'
export const FETCH_PREVIOUS_TEAMS_FAILURE = 'FETCH_PREVIOUS_TEAMS_FAILURE'

export const FETCH_GET_SCRUM_MASTER_REQUEST = 'FETCH_GET_SCRUM_MASTER_REQUEST'
export const FETCH_GET_SCRUM_MASTER_SUCCESS = 'FETCH_GET_SCRUM_MASTER_SUCCESS'
export const FETCH_GET_SCRUM_MASTER_FAILURE = 'FETCH_GET_SCRUM_MASTER_FAILURE'

export const FETCH_SET_SCRUM_MASTER_REQUEST = 'FETCH_SET_SCRUM_MASTER_REQUEST'
export const FETCH_SET_SCRUM_MASTER_SUCCESS = 'FETCH_SET_SCRUM_MASTER_SUCCESS'
export const FETCH_SET_SCRUM_MASTER_FAILURE = 'FETCH_SET_SCRUM_MASTER_FAILURE'

export const CREATE_TEAMS_REQUEST = 'CREATE_TEAMS_REQUEST'
export const CREATE_TEAMS_SUCCESS = 'CREATE_TEAMS_SUCCESS'
export const CREATE_TEAMS_FAILURE = 'CREATE_TEAMS_FAILURE'
