const members = [
  {
    id: 1,
    name: 'Shivam Asija',
    email: 'shivam.asija@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 2,
    name: 'Kanishka Singh',
    email: 'kanishka.singh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 3,
    name: 'Seemab Shaikh',
    email: 'seemab.shaikh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 4,
    name: 'Abhishek Kumar',
    email: 'abhishek.kumar@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 5,
    name: 'Saurabh Ranjan',
    email: 'Saurabh.Ranjan@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 6,
    name: 'Tom Van der Sloot',
    email: 'shivam.asija@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 7,
    name: 'Shilajeet Ray',
    email: 'kanishka.singh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 8,
    name: 'James McElroy',
    email: 'seemab.shaikh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 9,
    name: 'Davisson Flint',
    email: 'abhishek.kumar@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 10,
    name: 'Nathan Holland',
    email: 'Saurabh.Ranjan@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 11,
    name: 'Andrew Eber',
    email: 'shivam.asija@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 12,
    name: 'Dan Durnell',
    email: 'kanishka.singh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 13,
    name: 'Luis Soares',
    email: 'seemab.shaikh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 14,
    name: 'Bryce Williams',
    email: 'abhishek.kumar@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 15,
    name: 'Matthew Sigue',
    email: 'Saurabh.Ranjan@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 16,
    name: 'Ross Pallotta',
    email: 'shivam.asija@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 17,
    name: 'Justin Hamric',
    email: 'kanishka.singh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 18,
    name: 'Curtis Ward',
    email: 'seemab.shaikh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 19,
    name: 'Jacob Sowder',
    email: 'abhishek.kumar@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 20,
    name: 'Nicholas Kennedy',
    email: 'Saurabh.Ranjan@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 21,
    name: 'Nathan Burd',
    email: 'shivam.asija@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 22,
    name: 'Alex Griffin',
    email: 'kanishka.singh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 23,
    name: 'Danie Zheng',
    email: 'seemab.shaikh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 24,
    name: 'Maksim Galkin',
    email: 'abhishek.kumar@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 25,
    name: 'Serguei Pisarev',
    email: 'Saurabh.Ranjan@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 26,
    name: 'Noah Adams',
    email: 'shivam.asija@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 27,
    name: 'Nathan Snyder',
    email: 'kanishka.singh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 28,
    name: 'Andy Mason',
    email: 'seemab.shaikh@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
  {
    id: 29,
    name: 'John Macauley',
    email: 'abhishek.kumar@mandsconsulting.com',
    favouriteTech: 'ReactJs',
  },
]
export default members
